name: luzynski
favicon: null
layout_spectrum: 0
typography_spectrum: 0.86986
title: luzynski
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a29caa'
    - '#d1cfd4'
    - '#1e2d4e'
    - '#867a84'
    - '#000424'
  brandStrength: 0.5
  lightness: 0.9008957610931247
  saturation: 0.6875
  rhythmicContrast: 0.44742606789804995
purpose: []
